package org.jsirenia.array;

import java.util.Comparator;
import java.util.List;
import java.util.Map;

import org.jsirenia.util.callback.Callback11;
import org.jsirenia.util.callback.Callback20;
import org.jsirenia.util.callback.Callback21;
import org.jsirenia.util.callback.Callback30;
import org.jsirenia.util.callback.Callback31;
import org.jsirenia.util.callback.Callback41;

public interface Array<T> extends Iterable<T>{
		public List<T> toList();
		public <E> JArray<E> map(Callback11<E,T> cb);
		public <E> JArray<E> map(Callback21<E,T,Integer> cb);
		public <E> JArray<E> map(Callback31<E,T,Integer,JArray<T>> cb);
		public Object[] toArray();
		public T[] toArray(Class<T> clazz);
		public T reduce(Callback31<T,T,T,Integer> cb,T initValue);
		public T reduce(Callback41<T,T,T,Integer,JArray<T>> cb,T initValue);
		public T reduce(Callback21<T,T,T> cb,T initValue);
		public JArray<T> filter(Callback11<Boolean,T> cb);
		public JArray<T> filter(Callback21<Boolean,T,Integer> cb);
		public JArray<T> filter(Callback31<Boolean,T,Integer,JArray<T>> cb);
		public <R> Map<R,JArray<T>> groupBy(Callback11<R,T> cb);
		public <R> Map<R,JArray<T>> groupBy(Callback21<R,T,Integer> cb);
		public <R> Map<R,JArray<T>> groupBy(Callback31<R,T,Integer,JArray<T>> cb);
		public String join();
		public String join(String seperator);
		public boolean every(Callback31<Boolean,T,Integer,JArray<T>> cb);
		public boolean every(Callback21<Boolean,T,Integer> cb);
		public boolean every(Callback11<Boolean,T> cb);
		public boolean some(Callback31<Boolean,T,Integer,JArray<T>> cb);
		public boolean some(Callback21<Boolean,T,Integer> cb);
		public boolean some(Callback11<Boolean,T> cb);
		public int push(T v1,T v2,T v3,T v4,T v5,T v6,T v7,T v8,T v9,T v10);
		public int push(T v1,T v2,T v3,T v4,T v5,T v6,T v7,T v8,T v9);
		public int push(T v1,T v2,T v3,T v4,T v5,T v6,T v7,T v8);
		public int push(T v1,T v2,T v3,T v4,T v5,T v6,T v7);
		public int push(T v1,T v2,T v3,T v4,T v5,T v6);
		public int push(T v1,T v2,T v3,T v4,T v5);
		public int push(T v1,T v2,T v3,T v4);
		public int push(T v1,T v2,T v3);
		public int push(T v1,T v2);
		public int push(T v1);
		public T pop();
		public JArray<T> concat(JArray<T> a1,JArray<T> a2,JArray<T> a3,JArray<T> a4,JArray<T> a5,JArray<T> a6,JArray<T> a7,JArray<T> a8,JArray<T> a9,JArray<T> a10);
		public JArray<T> concat(JArray<T> a1,JArray<T> a2,JArray<T> a3,JArray<T> a4,JArray<T> a5,JArray<T> a6,JArray<T> a7,JArray<T> a8,JArray<T> a9);
		public JArray<T> concat(JArray<T> a1,JArray<T> a2,JArray<T> a3,JArray<T> a4,JArray<T> a5,JArray<T> a6,JArray<T> a7,JArray<T> a8);
		public JArray<T> concat(JArray<T> a1,JArray<T> a2,JArray<T> a3,JArray<T> a4,JArray<T> a5,JArray<T> a6,JArray<T> a7);
		public JArray<T> concat(JArray<T> a1,JArray<T> a2,JArray<T> a3,JArray<T> a4,JArray<T> a5,JArray<T> a6);
		public JArray<T> concat(JArray<T> a1,JArray<T> a2,JArray<T> a3,JArray<T> a4,JArray<T> a5);
		public JArray<T> concat(JArray<T> a1,JArray<T> a2,JArray<T> a3,JArray<T> a4);
		public JArray<T> concat(JArray<T> a1,JArray<T> a2,JArray<T> a3);
		public JArray<T> concat(JArray<T> a1,JArray<T> a2);
		public JArray<T> concat(JArray<T> a1);
		public JArray<T> concat(T v1,T v2,T v3,T v4,T v5,T v6,T v7,T v8,T v9,T v10);
		public JArray<T> concat(T v1,T v2,T v3,T v4,T v5,T v6,T v7,T v8,T v9);
		public JArray<T> concat(T v1,T v2,T v3,T v4,T v5,T v6,T v7,T v8);
		public JArray<T> concat(T v1,T v2,T v3,T v4,T v5,T v6,T v7);
		public JArray<T> concat(T v1,T v2,T v3,T v4,T v5,T v6);
		public JArray<T> concat(T v1,T v2,T v3,T v4,T v5);
		public JArray<T> concat(T v1,T v2,T v3,T v4);
		public JArray<T> concat(T v1,T v2,T v3);
		public JArray<T> concat(T v1,T v2);
		public JArray<T> concat(T v1);
		public int unshift();
		public T shift();
		public JArray<T> splice();
		public JArray<T> slice(int start);
		public JArray<T> slice(int start, int end);
		public void sort(Comparator<? super T> c);
		public void sort();
		public JArray<T> reverse();
		public T reduceRight(Callback41<T,T,T,Integer,JArray<T>> cb,T initValue);
		public T reduceRight(Callback31<T,T,T,Integer> cb,T initValue);
		public T reduceRight(Callback21<T,T,T> cb,T initValue);
		public int lastIndexOf(T t);
		public int indexOf(T t);
		public T find(Callback11<Boolean,T> cb);
		public int findIndex(Callback11<Boolean,T> cb);
		public JArray<T> fill(T t,int start,int end);
		public void forEach(Callback20<T,Integer> cb);
		public void forEach(Callback30<T,Integer,JArray<T>> cb);
		public boolean inclueds();
		public JArray<Integer> keys();
	}
